---
Name: mailgunsync
---
# API config
DPCNSW\SilverstripeMailgunSync\Connector\Base:
  api_domain: ''
  api_key: ''
  api_testmode: false
  sync_local_mime: false
  track_userform: false
  resubmit_failures : 2
  workaround_testmode: false
# Event config
MailgunEvent:
  secure_folder_name : 'SecureUploads'
  max_failures : 3
# Job config
DPCNSW\SilverstripeMailgunSync\FailedEventsJob:
  repeat_time : 86400
  time_of_day :
    hour : 11
    minute : 0
    second : 0
DPCNSW\SilverstripeMailgunSync\DeliveryCheckJob:
  repeat_time : 86400
  time_of_day :
    hour : 13
    minute : 0
    second : 0
---
Name: mailgunsyncuserform
Only:
  ModuleExists: userforms
---
# UserDefinedForm submission handling, if module exists
UserDefinedForm_Controller:
  extensions:
    - DPCNSW\SilverstripeMailgunSync\UserDefinedFormSubmissionExtension
